---
title: "Sesion 10 - Taller / Tarea 01"
author: "Juan Carlos Martinez Ovando"
date: "February 19, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Datos

```{r}
data <- read.csv("est46114_s06_data.csv")
data <- as.data.frame(data)
data <- as.matrix(data)
```

```{r}
T <- nrow(data); p <- ncol(data)-2
```

```{r}
datats <- ts(data[,c(3,p+2)],start=c(1970, 1), end=c(2010, 12), frequency=12)
plot(datats)
````

```{r}
acf(datats[,"Canada"])
```

```{r}
acf(datats[,"Zambia"])
```


# Medias dinamicas

```{r}
datats <- ts(data[,3:(p+2)],start=c(1970, 1), end=c(2010, 12), frequency=12)
Y <- T/12
years <- seq(1970,2010,1)
meansts <- NA * datats[c(1:41),]
t <- 1
for(t in 1:Y){
  meansts[t, ] <- colMeans(data[which(data[,"Year"]==years[t]),3:(p+2)])
}
```


```{r}
plot(meansts[,"Canada"])
```

```{r}
plot(meansts[,"Zambia"])
```

# Centros

```{r}
rep.row<-function(x,n){
   matrix(rep(x,each=n),nrow=n)
}
rep.col<-function(x,n){
   matrix(rep(x,each=n), ncol=n, byrow=TRUE)
}
```

```{r}
datatsc <- datats
t <- 1
for(t in 1:Y){
  datatsc[which(data[,"Year"]==years[t]),] <- datats[which(data[,"Year"]==years[t]),] - rep.row(meansts[t, ],12)
}
```

```{r}
plot(datatsc[,c("Canada","Zambia")])
```
```{r}
acf(datatsc[,"Canada"])
```

```{r}
acf(datatsc[,"Zambia"])
```


```{r}
scatter.smooth(datatsc[,c("Canada","Zambia")])
```